[package]
name = "maze"
version = "0.1.0"
authors = ["Alex.F <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
rand = "*"
anyhow = "1.0"

[dev-dependencies]
expect-test = "1.1"
